# Generated by Django 5.1.1 on 2024-09-26 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="myUser",
        ),
        migrations.DeleteModel(
            name="myModel",
        ),
    ]
